
name: publish-release
run-name: Publish Release
on:
  push:
    branches: ["main"]
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/checkout@v4
      - run: "bun ci"
      - run: "bin/bakery build"
      - run: "bin/bakery release"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
